! "main" (cells 136 length 17 width 31 generation 0)
! Period 4 c/4 spaceship
! Hartmut Holzwart
8k@!
..O.OO...O
OO...O...O..OO....O
..O.O...O....O..OO
......OOO..OO.OO..O
......OOO...OOOOO.O..OOO.O.O
........O.....O.O.OO..OOOO...O
.........OO......OO...........O
.........OO.......OOOOOOOOOOO.O
.
.........OO.......OOOOOOOOOOO.O
.........OO......OO...........O
........O.....O.O.OO..OOOO...O
......OOO...OOOOO.O..OOO.O.O
......OOO..OO.OO..O
..O.O...O....O..OO
OO...O...O..OO....O
..O.OO...O
