! "main" (cells 114 length 14 width 28 generation 0)
! First period 4 c/4 spaceship found with even symmetry.
! Hartmut Holzwart, October 1992
7k@!
..........O...OO.OO
........OOO........O
..O...OO.O..O.OO
OO...OOO..OOOO..O...O..OOO
..O...OOO...O...O...OOO...OO
..........OO....OOO...O...OO
......OO.OO....O.....OO.O
......OO.OO....O.....OO.O
..........OO....OOO...O...OO
..O...OOO...O...O...OOO...OO
OO...OOO..OOOO..O...O..OOO
..O...OO.O..O.OO
........OOO........O
..........O...OO.OO
