x = 104, y = 13
77boo$77bobobob4o$76boboobobob3o4boo5bo$62b3o3bo12bobo3bo3bobbooboobbo
$4bo5boo5boo5bo36boob5oboo3boo5b3obo3bo3bobo4b3o$bbobbooboobbo3bobboob
oobbo6bo13boo5boo4bobo5boboobo11boo4boob3obbobboo$3o4bobo3bobo3bobo4b
3obbooboboboo6bobbo3bo3bobb5o3bobo11b5o4bo4b3obb3o$oobbobb3oboo3boob3o
bbobboo5b3obob3o4b3obobo3bo3boo5b3o11boo13bobbobo$3obb3o4bo3bo4b3obb3o
bo5bobo3bobb3obboo5bo8b3obobbo27bo$bobobbo15bobbobobbo6boo13b3oboo13bo
$bbo23bo3bo9boo15bo$37booboo10bo3bo$37bo14bobbo!
Period 5 c/5 extensible spaceship.
This demonstrates how to make an arbitrarily large c/5 spaceship
by repeating one component a number of times.  The join between the
components can be "slipped" up or down by two cells, so as to make
a weaving spaceship like this one.
David I. Bell, April 1997
