#C B-heptomino (stabilizes at time 148)  This is a very common
#C    pattern.  It often arises with the cell at top left shifted one
#C    space to the left, which does not affect the subsequent evolution.
#C    B-heptominoes acquired particular importance in 1996 due
#C    to Dave Buckingham's work on B tracks - see in particular
#C    My Experience with B-heptominos in Oscillators.
	*.**
	***.
	.*..

