#C caterer (p3)  Found by Dean Hickerson, August 1989.  Compare
#C    with jam.  In terms of its minimum population of 12 this is
#C    the smallest p3 oscillator.  See also double caterer and
#C    triple caterer.
	..*.....
	*...****
	*...*...
	*.......
	...*....
	.**.....
.
.
.
.
#C    More generally, any oscillator which serves up a bit in the
#C    same manner may be referred to as a ceterer.

