#C hammer  To hammer a LWSS, MWSS or HWSS is to smash things into
#C    the rear end of it in order to transform it into a different type
#C    of spaceship.  A hammer is the object used to do the hammering.
#C    In the following example by Dieter Leithner a LWSS is hammered by
#C    two more LWSS to make it into a MWSS.
	*..*................
	....*...**..........
	*...*..***.....****.
	.****..**.*....*...*
	........***....*....
	.........*......*..*

