#C x66  (c/2 orthogonally, p4)  Found by Hartmut Holzwart, July 1992.
#C    Half of this can be escorted by a HWSS.  The name refers to the
#C    fact that every cell (live or dead) has at most 6 live neighbours
#C    (in contrast to spaceships based on LWSS, MWSS or HWSS).
#C    In fact this spaceship was found by a search with this restriction.
	..*......
	**.......
	*..***..*
	*....***.
	.***..**.
	.........
	.***..**.
	*....***.
	*..***..*
	**.......
	..*......

