x = 47, y = 39
boo$boo$boo$bo10boobboo4bobboo12boo$obo9booboo6boobo12boo$oboo12bobo6b
o$17boo4b3o$$boo14boo4b3o$boo13bobo6bo$15boo6boobo$12bo3boo4bobboo$11b
oo$11bobo6$28bo$26bobo$27boo$$23boo$22boo$24bo$$9boo4bobboo17boo$8boo
6boobo16bobbo$9bobo6bo17bobbo3boo$10boo4b3o18boo4boo$$10boo4b3o24bo$9b
obo6bo23bobo$5booboo6boobo12boo8bobbo$5boobboo4bobboo12boo9bobbo$$43bo
bbo$43boo!
Period 184 glider relay using p46 shuttles and p8 blockers.
Multiple gliders can be in the loop.
