! "main" (cells 44 length 15 width 30 generation 0)
! Period 72 oscillator.
! A glider gun has been built based on this.
! Robert Wainwright.
5k14h@!
..................O
.................O.OO
.................O.OO
..................OO
.
.......O.............O
.......OO............OO
.
.
......O.O
.....O..................OO
.O..O....O..........OO.O..O.OO
OO.O..O.OO..........OO..O....O
....OO...................O
..........................O.O
