! "main" (cells 68 length 18 width 18 generation 0)
! First known non-glider to travel diagonally at c/4.
! Dean Hickerson, December 1989
9k9h@!
....O..O
....OOO.O
...OO
..O.OO...O
OOOO...OO.O
.O.O...OOOO
.O.......O
O...OO....O.OO
.O..OO......O.O
...O.OO.........O
....OO.O.....O..O
...............OO
.......OO........O
.......O..O....O.O
........O.......OO
...........O.O
.........OOO..O
............OOO
