! "main" (cells 90 length 18 width 23 generation 0)
! Period 4 c/4 spaceship with even symmetry.
! Hartmut Holzwart
9k@!
...........O......OO
...........OO.OO..OOO.O
...........O....O...O.O
..............OO..OOO.O
..O...OOO.........OO
OO...OOO..O.O
..O...OOOOOO.O
.............O
......OO
......OO
.............O
..O...OOOOOO.O
OO...OOO..O.O
..O...OOO.........OO
..............OO..OOO.O
...........O....O...O.O
...........OO.OO..OOO.O
...........O......OO
