! "main" (cells 113 length 17 width 23 generation 0)
! One of the first new period 4 c/2 glide-reflection spaceships
! David I. Bell
8k@!
.........O
......OO.O
......O...O....OO..OO
...O.O..OO....OOO..OOOO
..OOOOO...O.O.OOO.O..OO
.OO.....OO.OO
OO....O......O.O..OO
.OO....OOOOOOOO
......O.........O..O
.OO....OOOOOOOOO
OO....O........OOO
.OO.....OOOO.OO.OO..O
..OOOOO.........OO..O
...O.O..OOO..OOO.O.OO
......O
......OO.O.O
.........O
