x = 24, y = 51
oo15boo$oo15boo6$15bo$14bobo$14bobo$15bo$11boo$6boobbobbo$5bobbobobbo$
5bobbobobbo$5bobbobboo$6boo$3bo$bbobo$bbobo$3bo$21boo$21boo$10boo$10b
oo$22boo$oo10bo7boboo$oo9bobo6bo$15boo3bo$16bo3bobbo$10boo9boo$$13bobo
6$11boo$11bo$11b3o$21boo$15boo4boo$15boo$$20boo$20boobo$23bo$23bo$20bo
bbo$21boo!

A period 144 glider gun based on Achim Flammenkamp's period 144 oscillator
and Robert Wainwright's period 72 oscillator.
Bill Gosper, 1994
