x = 44, y = 41
17boo6boo$17boo6boo7$boo38boo$obo38bobo$oboboo32boobobo$bobobo32bobobo
$3bo36bo$bbobbo13bo4bo13bobbo$bbo15boo4boo15bo$bbo3bo10bo8bo10bo3bo$bb
o3bo11boo4boo11bo3bo$bbo16bo4bo16bo$bbobbo32bobbo$3bo36bo$bobobo32bobo
bo$oboboo32boobobo$obo38bobo$boo38boo4$27boo$27bo$28b3o$8boo20bo$7bobo
14boo$7bo16boo$6boo4$22boo$22bobo$24bo$24boo!
Period 44 glider gun.
Based on an oscillator and glider producing reaction by David Buckingham.
Paul Callahan, February 1997

