x = 48, y = 34
boo29boo4boo4boo$boo28bobbobo4bobobbo$31b3o10boobo$13boo7b4o8boo6boobb
oo$oo10bobbo6bo3bo6bobb6obbo$oo9boobbo10bo6boo8booboo$12bobbo4boboobo
19bobo$13bo6b3o22bo$43b3o$13bo6b3o19bo$12bobbo4boboo18boo$oo9boobbo8bo
$oo10bobbo6boo$13boo7bo$$boo$boo40bo$44bo$29b3o3b3o4b3o$28bobbo3bobbo$
32bobo$32bobo$32bobo$28bobbo3bobbo$29bo7bo7$25boo13boo$25boobboo5boobb
oo$29boo5boo!
Period 92 glider gun based on a p46 gun by Dieter Leithner.
David I. Bell, October 1996
