#C bi-loaf  This term has been used in at least three different senses.
#C    A bi-loaf can be half a bakery
	.*.....
	*.*....
	*..*...
	.**.*..
	...*.*.
	...*..*
	....**.
.
.
.
.
#C    or it can be the following much less common still life
	..*....
	.*.*...
	*..*...
	.**.**.
	...*..*
	...*.*.
	....*..
.
.
.
.
#C    or the following pure glider generator
	..*.
	.*.*
	*..*
	.**.
	*..*
	*.*.
	.*..

