#C pulsar (p3)  Despite its size, this is the fourth most common
#C    oscillator (and by far the most common of period greater than 2)
#C    and was found very early on by Conway.  See also pre-pulsar and
#C    pulsar quadrant.
	..***...***..
	.............
	*....*.*....*
	*....*.*....*
	*....*.*....*
	..***...***..
	.............
	..***...***..
	*....*.*....*
	*....*.*....*
	*....*.*....*
	.............
	..***...***..

