#C traffic jam  Any traffic light hassler, such as traffic circle.
#C    The term is also applied to the following reaction, used in most
#C    traffic light hasslers, in which two traffic lights interact in such
#C    a way as to reappear after 25 generations with an extra 6 spaces
#C    between them.
	..***...........
	...........***..
	*.....*.........
	*.....*..*.....*
	*.....*..*.....*
	.........*.....*
	..***...........
	...........***..

