#C weekender (2c/7 orthogonally, p7)  Found by David Eppstein in
#C    January 2000.  In April 2000 Stephen Silver found a tagalong for a
#C    pair of weekenders.  At present, n weekenders pulling n-1 tagalongs
#C    constitute the only known spaceships of this speed or period.
	.*............*.
	.*............*.
	*.*..........*.*
	.*............*.
	.*............*.
	..*...****...*..
	......****......
	..****....****..
	................
	....*......*....
	.....**..**.....

