! "main" (cells 71 length 8 width 31 generation 0)
! Smallest known period 2 spaceship.
! The first of the non-standard spaceships to be found.
! Dean Hickerson, July 28 1989
15h@!
......O.................O
.....OOO...............OOO
...OO.OOO.............OOO.OO
....O..O.OO....O....OO.O..O
.OO.O....O.O.OO.OO.O.O....O.OO
.OO.O.O..O.O.......O.O..O.O.OO
.O........OOO.O.O.OOO........O
OO.......OO.........OO.......OO
