x = 44, y = 31
17boo6boo$17boo6boo6$boo38boo$obo38bobo$oboboo32boobobo$bobobo32bobobo
$3bo36bo$bobbo34bobbo$4bo13boo4boo13bo$o3bo12bobo4bobo12bo3bo$o3bo12bo
8bo12bo3bo$4bo12bobo4bobo12bo$bobbo13boo4boo13bobbo$3bo36bo$bobobo32bo
bobo$oboboo32boobobo$obo38bobo$boo38boo7$17boo6boo$17boo6boo!

An improvement on David Buckingham's period 44 oscillator.
This one removes two blocks from the oscillator.
Noam Elkies, April 1996
