! "main" (cells 79 length 25 width 17 generation 0)
! Period 8 blinker puffer (using period 4 engine)
! David I. Bell, July 1992
1l@!
.............OOO
............OOOOO
...........OO.OOO
............OO
.
.
.........O.O
..O.....O..O
.OOOOO...O.O
OO...OO.OO
.O.......O
..OO..O..O
..........O
..OO..O..O
.O.......O
OO...OO.OO
.OOOOO...O.O
..O.....O..O
.........O.O
.
.
............OO
...........OO.OOO
............OOOOO
.............OOO
