#C Achim's p4 (p4)  Dave Buckingham found this in a less compact form
#C    (using two halves of sombreros) in 1976.  The form shown here was
#C    found by Achim Flammenkamp in 1988.  The rotor is two copies of
#C    the rotor of 1-2-3-4, so the oscillator is sometimes called the
#C    "dual 1-2-3-4".
	..**...**..
	.*..*.*..*.
	.*.**.**.*.
	**.......**
	..*.*.*.*..
	**.......**
	.*.**.**.*.
	.*..*.*..*.
	..**...**..

