#C eater3 (p1)  This large symmetric eater, found by Dave Buckingham,
#C    has a very different eating action from the eater1 and eater2.
#C    The loaf can take bites out things, being flipped over in the
#C    process.  The rest of the object merely flips it back again.
	.........**.
	....**..*..*
	.*..*....*.*
	*.*.*.....*.
	.*..*.**....
	....*..*....
	.....*....*.
	......*****.
	............
	........*...
	.......*.*..
	........*...

