#C mold (p4)  Found by Achim Flammenkamp in 1988, but not widely known
#C    until Dean Hickerson rediscovered it (and named it) in August 1989.
#C    Compare with jam.  In terms of its minimum population of 12 it
#C    ties with mazing as the smallest p4 oscillator.  But in terms
#C    of its 6x6 bounding box it wins outright.  In fact, of all
#C    oscillators that fit in a 6x7 box it is the only one with period
#C    greater than 2.
	...**.
	..*..*
	*..*.*
	....*.
	*.**..
	.*....

