#C onion rings  For each integer n>1 onion rings of order n is a stable
#C    agar of density 1/2 obtained by tiling the plane with a certain
#C    4n x 4n pattern.  The tile for order 3 onion rings is shown below -
#C    the reader should then be able to deduce the form of tiles of other
#C    orders.
	......******
	.****.*....*
	.*..*.*.**.*
	.*..*.*.**.*
	.****.*....*
	......******
	******......
	*....*.****.
	*.**.*.*..*.
	*.**.*.*..*.
	*....*.****.
	******......

