#C sidecar  A small tagalong for a HWSS that was found by Hartmut
#C    Holzwart in 1992.  The resulting spaceship (shown below) has a
#C    phase with only 24 cells, making it in this respect the smallest
#C    known spaceship other than the standard spaceships and some trivial
#C    two-spaceship flotillas derived from them.  Note also that a HWSS
#C    can support two sidecars at once.
	.*......
	*.....*.
	*.....*.
	*****.*.
	........
	....**..
	..*....*
	.*......
	.*.....*
	.******.

