! "main" (cells 53 length 23 width 14 generation 0)
! A "boat stretcher" object which moves diagonally with period 4 which
! leaves behind a growing long boat.
! Spaceship by Tim Coe, February 1996
! Stretcher by Noam Elkies, February 1996
10k@!
...........O
..........OO
.
........OOO
........OOO
.
.
.......OOO
.......OO
.O....O..OOO.O
O.O...OO.O...O
.O....OO.OO.OO
......OOO
......OO
......O
......OO
.......O.O
...........O
.........O..O
..........O..O
..........O
.............O
...........OOO
