! "main" (cells 65 length 19 width 22 generation 14)
! A period 16 backwards rake made by perturbing Tim Coe's puffer engine.
! Paul Callahan, October 1995
7k22h@!
......OOOOOO
.....O.....O
...........O
.....O....O
.......OO
.
...................OO
.O...........O.OOOO.OO
O...........OO..OOOOO
OOO..........O...OOO
.
.
.................OOOO
................O...O
....................O
...........OO...O..O
.......OOOO.OO
.......OOOOOO
........OOOO
